// 配音員完整配置
// 包含詳細描述、年齡段、風格標籤和試聽 URL

// 語言類型
export type VoiceLanguage = "cantonese" | "mandarin" | "english" | "clone";

// 年齡段類型
export type AgeGroup = "child" | "teen" | "young" | "adult" | "middle" | "elder";

// 風格類型
export type VoiceStyle = 
  | "narrator"      // 旁白
  | "character"     // 角色
  | "news"          // 新聞
  | "commercial"    // 廣告
  | "storytelling"  // 故事
  | "assistant"     // 助手
  | "cartoon"       // 卡通
  | "emotional"     // 情感
  | "professional"; // 專業

// 配音員接口
export interface VoiceActorConfig {
  id: string;
  name: string;
  gender: "male" | "female";
  type: "narrator" | "character";
  language: VoiceLanguage;
  ageGroup: AgeGroup;
  style: VoiceStyle[];
  description: string;
  useCases: string[];  // 適用場合
  voice: string;
  sampleText: string;
  sampleUrl?: string;  // 試聽 URL
  tags: string[];
  kreadoVoiceId: string;
  kreadoVoiceSource: number;
}

// ============================================
// 粵語配音員 (Cantonese) - MiniMax voiceSource: 5
// ============================================

export const CANTONESE_VOICE_ACTORS: Record<string, VoiceActorConfig> = {
  // === 男聲 - 成年 ===
  "cantonese-male-narrator": {
    id: "cantonese-male-narrator",
    name: "書聲儒雅",
    gender: "male",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "storytelling", "professional"],
    description: "渾厚穩重的粵語男聲，音色溫潤有磁性，吐字清晰",
    useCases: ["紀錄片旁白", "有聲書朗讀", "品牌宣傳", "教育內容"],
    voice: "alloy",
    sampleText: "大家好，歡迎嚟到我嘅頻道，今日同你哋分享一個精彩嘅故事。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/db43a80789d343c6843d3f03191360cd.mp3",
    tags: ["旁白", "敘述", "紀錄片", "專業"],
    kreadoVoiceId: "ai_000046",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-young": {
    id: "cantonese-male-young",
    name: "磁性男聲",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character", "emotional"],
    description: "年輕有活力的粵語男聲，聲線清亮有感染力",
    useCases: ["年輕男主角", "愛情故事", "青春劇情", "日常對話"],
    voice: "echo",
    sampleText: "哎，你講嘅係唔係真㗎？我要試下先得！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/1f67f1eddb54492386bbf979d5d1f55c.mp3",
    tags: ["年輕", "活潑", "男主角", "愛情"],
    kreadoVoiceId: "ai_charming_m_01",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-mature": {
    id: "cantonese-male-mature",
    name: "成熟男聲",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "middle",
    style: ["character", "professional"],
    description: "成熟穩重的粵語男聲，帶有威嚴和可靠感",
    useCases: ["父親角色", "老闆角色", "導師角色", "權威人物"],
    voice: "onyx",
    sampleText: "呢件事唔簡單，要諗清楚先得。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/0c499ea708404312b3a1d3d847c3c3bb.mp3",
    tags: ["成熟", "穩重", "父親", "老闆"],
    kreadoVoiceId: "ai_000141",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-deep": {
    id: "cantonese-male-deep",
    name: "沉穩男",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "storytelling"],
    description: "深沉有磁性的男聲，帶有神秘感和故事感",
    useCases: ["懸疑故事", "神秘角色", "深夜電台", "哲理內容"],
    voice: "fable",
    sampleText: "命運嘅輪盤已經開始轉動...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/ceec0ba8719844e1b159e39698001aa6.mp3",
    tags: ["深沉", "磁性", "神秘", "故事"],
    kreadoVoiceId: "ai_charming_m_05",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-energetic": {
    id: "cantonese-male-energetic",
    name: "雲逸",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character", "commercial"],
    description: "充滿活力的男聲，聲音明亮有朝氣",
    useCases: ["運動內容", "冒險故事", "遊戲解說", "活力廣告"],
    voice: "echo",
    sampleText: "衝呀！我哋一定得㗎！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/ee86e11a6e344ecb9bfcf7def6c484e1.mp3",
    tags: ["活力", "運動", "冒險", "熱血"],
    kreadoVoiceId: "ai_chongyun",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-elegant": {
    id: "cantonese-male-elegant",
    name: "迪曜",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "adult",
    style: ["character", "professional"],
    description: "優雅紳士的男聲，帶有貴族氣質",
    useCases: ["紳士角色", "高端品牌", "優雅場合", "古典故事"],
    voice: "alloy",
    sampleText: "請容許我為你介紹...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/be13d115112c474d8988b2d8a85affff.mp3",
    tags: ["優雅", "紳士", "貴族", "高端"],
    kreadoVoiceId: "ai_diluke",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-dj": {
    id: "cantonese-male-dj",
    name: "音韻俊朗",
    gender: "male",
    type: "narrator",
    language: "cantonese",
    ageGroup: "young",
    style: ["narrator", "commercial"],
    description: "DJ 風格的男聲，聲音有節奏感和感染力",
    useCases: ["電台節目", "音樂介紹", "活動主持", "潮流內容"],
    voice: "echo",
    sampleText: "各位聽眾朋友，歡迎收聽今晚嘅節目！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/7babf8c82b814e8eb2edd7a1630880a0.mp3",
    tags: ["DJ", "電台", "主持", "潮流"],
    kreadoVoiceId: "ai_dj_m_01",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-boy": {
    id: "cantonese-male-boy",
    name: "中二君",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "teen",
    style: ["character", "cartoon"],
    description: "中二少年風格的男聲，帶有熱血和幻想感",
    useCases: ["動漫角色", "遊戲角色", "熱血少年", "搞笑內容"],
    voice: "echo",
    sampleText: "我嘅右手封印住強大嘅力量！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/de079ad85855455aabf3bf9509295d27.mp3",
    tags: ["中二", "少年", "動漫", "熱血"],
    kreadoVoiceId: "ai_bili_712",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-scholar": {
    id: "cantonese-male-scholar",
    name: "博文",
    gender: "male",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "professional"],
    description: "學者風格的男聲，聲音沉穩有學識感",
    useCases: ["教育內容", "知識講解", "學術分享", "科普視頻"],
    voice: "alloy",
    sampleText: "根據研究顯示，呢個現象背後有幾個重要原因...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/9535eb9ccfbc4fc7ae09ac2cf8d376fe.mp3",
    tags: ["學者", "教育", "知識", "專業"],
    kreadoVoiceId: "ai_baodewen4_712",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-hero": {
    id: "cantonese-male-hero",
    name: "凱夜",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character", "storytelling"],
    description: "英雄風格的男聲，聲音堅定有正義感",
    useCases: ["英雄角色", "正義故事", "動作場景", "勵志內容"],
    voice: "onyx",
    sampleText: "我會保護你哋，無論發生咩事！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/0d21f349bf50467bb185a82472552535.mp3",
    tags: ["英雄", "正義", "堅定", "保護"],
    kreadoVoiceId: "ai_kaiya",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-cold": {
    id: "cantonese-male-cold",
    name: "冷傲青鋒",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character"],
    description: "冷酷傲慢的男聲，帶有距離感和高冷氣質",
    useCases: ["高冷角色", "反派角色", "武俠故事", "霸道總裁"],
    voice: "onyx",
    sampleText: "哼，你以為你係邊個？",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/da54ec59097940fc81679f2140c17e6a.mp3",
    tags: ["冷酷", "高冷", "傲慢", "霸道"],
    kreadoVoiceId: "ai_lilianhua_712",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-dragon": {
    id: "cantonese-male-dragon",
    name: "龍嘯威聲",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "adult",
    style: ["character", "storytelling"],
    description: "威嚴霸氣的男聲，聲音洪亮有氣勢",
    useCases: ["王者角色", "武俠大俠", "史詩故事", "氣勢宣傳"],
    voice: "onyx",
    sampleText: "天下英雄，盡在此處！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/7976101f21c64634976cf3e673a11b22.mp3",
    tags: ["威嚴", "霸氣", "王者", "武俠"],
    kreadoVoiceId: "ai_longxiao_712",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-sunny": {
    id: "cantonese-male-sunny",
    name: "陽光健翔",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character", "commercial"],
    description: "陽光開朗的男聲，聲音溫暖有親和力",
    useCases: ["陽光男孩", "運動員角色", "健康廣告", "正能量內容"],
    voice: "echo",
    sampleText: "今日天氣咁好，一齊去做運動啦！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/5ae1b04de0694c3c9a6c3955391f8c7a.mp3",
    tags: ["陽光", "健康", "運動", "開朗"],
    kreadoVoiceId: "ai_jianshenjiaolian_712",
    kreadoVoiceSource: 5,
  },

  // === 女聲 - 成年 ===
  "cantonese-female-narrator": {
    id: "cantonese-female-narrator",
    name: "靈韻",
    gender: "female",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "storytelling"],
    description: "溫柔優雅的粵語女聲，音色甜美有感染力",
    useCases: ["有聲書朗讀", "故事旁白", "品牌宣傳", "溫馨內容"],
    voice: "nova",
    sampleText: "喺呢個安靜嘅夜晚，月光照喺小鎮嘅街道上...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/e7b2df6dee7f419e863f1dfc994d7993.mp3",
    tags: ["旁白", "敘述", "溫柔", "優雅"],
    kreadoVoiceId: "ai_charming_f_01",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-young": {
    id: "cantonese-female-young",
    name: "靈音姬",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character", "emotional"],
    description: "年輕活潑的粵語女聲，聲音清脆有朝氣",
    useCases: ["年輕女主角", "愛情故事", "青春劇情", "日常對話"],
    voice: "shimmer",
    sampleText: "哇，真係好靚呀！我唔敢相信呀！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/09b07749d50b41fa893bacb57ebbd849.mp3",
    tags: ["年輕", "活潑", "女主角", "青春"],
    kreadoVoiceId: "ai_charming_f_22",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-mature": {
    id: "cantonese-female-mature",
    name: "靈汐",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "middle",
    style: ["character", "professional"],
    description: "成熟優雅的粵語女聲，帶有知性和溫暖感",
    useCases: ["母親角色", "職場女性", "知性角色", "溫馨故事"],
    voice: "alloy",
    sampleText: "你要記住，做人最緊要係誠實。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/0e51c773ec3a498fbc7dc024b6f6d8c7.mp3",
    tags: ["成熟", "優雅", "母親", "知性"],
    kreadoVoiceId: "ai_charming_f_23",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-sweet": {
    id: "cantonese-female-sweet",
    name: "靈音妹",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character", "assistant"],
    description: "甜美可愛的女聲，聲音軟糯有親和力",
    useCases: ["可愛角色", "客服助手", "甜蜜內容", "少女角色"],
    voice: "shimmer",
    sampleText: "你好呀～有咩可以幫到你㗎？",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/c1e58ecbc81d457d96e3449491ea8376.mp3",
    tags: ["甜美", "可愛", "助手", "少女"],
    kreadoVoiceId: "ai_charming_f_24",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-wise": {
    id: "cantonese-female-wise",
    name: "知薇",
    gender: "female",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "professional"],
    description: "知性優雅的女聲，聲音沉穩有學識感",
    useCases: ["知識講解", "教育內容", "專業解說", "科普視頻"],
    voice: "nova",
    sampleText: "今日我哋嚟了解一下呢個有趣嘅現象...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/1387f57365ef410685aef35e8e5fc8a1.mp3",
    tags: ["知性", "專業", "教育", "優雅"],
    kreadoVoiceId: "ai_charming_f_25",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-dj": {
    id: "cantonese-female-dj",
    name: "星瀾",
    gender: "female",
    type: "narrator",
    language: "cantonese",
    ageGroup: "young",
    style: ["narrator", "commercial"],
    description: "DJ 風格的女聲，聲音有節奏感和活力",
    useCases: ["電台節目", "音樂介紹", "活動主持", "潮流內容"],
    voice: "shimmer",
    sampleText: "各位聽眾朋友，準備好未？音樂嚟啦！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/8d1252e4c7af4089808888d0e69ecc6b.mp3",
    tags: ["DJ", "電台", "主持", "活力"],
    kreadoVoiceId: "ai_dj_f_01",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-elegant2": {
    id: "cantonese-female-elegant2",
    name: "音韻霓裳",
    gender: "female",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "storytelling"],
    description: "優雅華麗的女聲，聲音如詩如畫",
    useCases: ["古風故事", "優雅場合", "高端品牌", "藝術內容"],
    voice: "nova",
    sampleText: "月華如水，流淌喺呢個寧靜嘅夜晚...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/0f0b6b5eae9a432e85822ec69fa5cb01.mp3",
    tags: ["優雅", "華麗", "古風", "藝術"],
    kreadoVoiceId: "ai_dj_f_02",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-fairy": {
    id: "cantonese-female-fairy",
    name: "甘霓",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character", "storytelling"],
    description: "仙氣飄飄的女聲，聲音空靈有夢幻感",
    useCases: ["仙俠角色", "夢幻故事", "奇幻內容", "神秘角色"],
    voice: "nova",
    sampleText: "凡人，你可知道呢度係仙界？",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/d6d1bf3a729f47a0b8884869249b5e3f.mp3",
    tags: ["仙氣", "空靈", "夢幻", "仙俠"],
    kreadoVoiceId: "ai_ganyu",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-cute": {
    id: "cantonese-female-cute",
    name: "胡桃音姬",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "teen",
    style: ["character", "cartoon"],
    description: "俏皮可愛的女聲，聲音活潑有趣",
    useCases: ["可愛角色", "搞笑內容", "遊戲角色", "輕鬆故事"],
    voice: "shimmer",
    sampleText: "嘻嘻，俾我捉到你啦！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/f3c24f50d0b8407bbdc56ec79226292b.mp3",
    tags: ["俏皮", "可愛", "活潑", "搞笑"],
    kreadoVoiceId: "ai_hutao",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-clear": {
    id: "cantonese-female-clear",
    name: "清音姬",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character", "professional"],
    description: "清冷高貴的女聲，聲音清澈有氣質",
    useCases: ["高冷角色", "職場精英", "冷艷美人", "專業場合"],
    voice: "nova",
    sampleText: "請你認真啲，呢件事唔係玩嘅。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/2b58de6a172f48e1b6f35557e5fd1492.mp3",
    tags: ["清冷", "高貴", "專業", "氣質"],
    kreadoVoiceId: "ai_keqing",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-loli": {
    id: "cantonese-female-loli",
    name: "可麗音",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "teen",
    style: ["character", "cartoon"],
    description: "蘿莉風格的女聲，聲音甜美稚嫩",
    useCases: ["蘿莉角色", "可愛動漫", "兒童內容", "萌系角色"],
    voice: "shimmer",
    sampleText: "哥哥～你陪我玩好唔好？",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/656e89a054fd4342b27445a79da822c4.mp3",
    tags: ["蘿莉", "甜美", "稚嫩", "萌"],
    kreadoVoiceId: "ai_keli",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-assistant": {
    id: "cantonese-female-assistant",
    name: "晶靈助手",
    gender: "female",
    type: "narrator",
    language: "cantonese",
    ageGroup: "young",
    style: ["assistant", "professional"],
    description: "AI 助手風格的女聲，聲音清晰專業",
    useCases: ["語音助手", "客服系統", "導航語音", "智能設備"],
    voice: "nova",
    sampleText: "你好，我係你嘅智能助手，有咩可以幫到你？",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/0c77bb6b9d9146359c7689c5d4a29a15.mp3",
    tags: ["助手", "AI", "專業", "清晰"],
    kreadoVoiceId: "ai_jingling",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-teacher": {
    id: "cantonese-female-teacher",
    name: "教導嚴音",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "adult",
    style: ["character", "professional"],
    description: "嚴肅認真的女聲，聲音有權威感",
    useCases: ["老師角色", "教育內容", "嚴肅場合", "訓導角色"],
    voice: "alloy",
    sampleText: "同學們，請認真聽講！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/758f38577665404898fea8e9d6d51b12.mp3",
    tags: ["老師", "嚴肅", "權威", "教育"],
    kreadoVoiceId: "ai_jiaodaozhuren_712",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-gentle": {
    id: "cantonese-female-gentle",
    name: "璃紗",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character", "emotional"],
    description: "溫柔體貼的女聲，聲音輕柔有愛意",
    useCases: ["溫柔角色", "愛情故事", "治癒內容", "溫馨場景"],
    voice: "nova",
    sampleText: "唔好擔心，我會一直陪住你。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/e431c5e31d9745699388d0db339ac816.mp3",
    tags: ["溫柔", "體貼", "愛情", "治癒"],
    kreadoVoiceId: "ai_lisha",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-ice": {
    id: "cantonese-female-ice",
    name: "冰嬌夢音",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character"],
    description: "冰冷傲嬌的女聲，聲音帶有距離感",
    useCases: ["傲嬌角色", "冷艷美人", "高冷女主", "反差萌"],
    voice: "nova",
    sampleText: "哼，唔係因為你我先咁做㗎！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/5173f69b6db74b06983852357967b2bd.mp3",
    tags: ["傲嬌", "冰冷", "高冷", "反差"],
    kreadoVoiceId: "ai_bingjiaoxuemei_712",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-proud": {
    id: "cantonese-female-proud",
    name: "傲嬌芳",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character", "emotional"],
    description: "傲嬌可愛的女聲，聲音帶有小脾氣",
    useCases: ["傲嬌角色", "可愛女友", "輕喜劇", "日常對話"],
    voice: "shimmer",
    sampleText: "我...我先唔係擔心你呢！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/fdf2ee6ab4cd4c1fb8b1b888cb652d8b.mp3",
    tags: ["傲嬌", "可愛", "小脾氣", "女友"],
    kreadoVoiceId: "ai_heqifang_712",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-breeze": {
    id: "cantonese-female-breeze",
    name: "輕聲清嵐",
    gender: "female",
    type: "narrator",
    language: "cantonese",
    ageGroup: "young",
    style: ["narrator", "storytelling"],
    description: "輕柔清新的女聲，聲音如微風般舒適",
    useCases: ["ASMR 內容", "睡前故事", "冥想引導", "放鬆內容"],
    voice: "nova",
    sampleText: "閉上眼睛，深呼吸，感受呢一刻嘅寧靜...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/accc08de8770421e8e0a86ded8f58985.mp3",
    tags: ["輕柔", "清新", "ASMR", "放鬆"],
    kreadoVoiceId: "ai_enina_712",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-morning": {
    id: "cantonese-female-morning",
    name: "晨曦露",
    gender: "female",
    type: "narrator",
    language: "cantonese",
    ageGroup: "young",
    style: ["narrator", "commercial"],
    description: "清新明亮的女聲，聲音如晨曦般溫暖",
    useCases: ["早安問候", "正能量內容", "清新廣告", "生活分享"],
    voice: "shimmer",
    sampleText: "早晨！新嘅一日又開始啦，加油！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/baf71ee27f8b47979beb9879f8722fce.mp3",
    tags: ["清新", "明亮", "早安", "正能量"],
    kreadoVoiceId: "ai_chenguilu_712",
    kreadoVoiceSource: 5,
  },

  // === 童聲 ===
  "cantonese-child-boy": {
    id: "cantonese-child-boy",
    name: "金小猴",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "child",
    style: ["character", "cartoon"],
    description: "活潑可愛的男童聲，聲音稚嫩有童趣",
    useCases: ["兒童角色", "動畫配音", "兒童節目", "童話故事"],
    voice: "echo",
    sampleText: "媽咪，我想食糖糖！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/b7786e600724494abc5ccb4456afea2d.mp3",
    tags: ["童聲", "男孩", "可愛", "活潑"],
    kreadoVoiceId: "ai_jinsihou_712",
    kreadoVoiceSource: 5,
  },
  "cantonese-child-girl": {
    id: "cantonese-child-girl",
    name: "甘霓女童",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "child",
    style: ["character", "cartoon"],
    description: "甜美可愛的女童聲，聲音清脆稚嫩",
    useCases: ["兒童角色", "動畫配音", "兒童節目", "童話故事"],
    voice: "shimmer",
    sampleText: "爸爸，我想要個洋娃娃！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/09b07749d50b41fa893bacb57ebbd849.mp3",
    tags: ["童聲", "女孩", "可愛", "甜美"],
    kreadoVoiceId: "ai_charming_f_22",
    kreadoVoiceSource: 5,
  },
  "cantonese-child-cute": {
    id: "cantonese-child-cute",
    name: "萌娃童音",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "child",
    style: ["character", "cartoon"],
    description: "奶聲奶氣的童聲，聲音超萌超可愛",
    useCases: ["幼兒角色", "可愛動畫", "兒童廣告", "萌系內容"],
    voice: "echo",
    sampleText: "媽媽抱抱～我要抱抱～",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/b7786e600724494abc5ccb4456afea2d.mp3",
    tags: ["童聲", "萌娃", "奶聲奶氣", "超萌"],
    kreadoVoiceId: "ai_jinsihou_712",
    kreadoVoiceSource: 5,
  },

  // === 老年聲 ===
  "cantonese-elder-male": {
    id: "cantonese-elder-male",
    name: "老國聲",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "elder",
    style: ["character", "storytelling"],
    description: "慈祥智慧的老年男聲，聲音沉穩有歷練感",
    useCases: ["爺爺角色", "智者角色", "歷史故事", "人生哲理"],
    voice: "fable",
    sampleText: "後生仔，聽阿爺講個故事俾你聽...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/00ecc0b9126b4bef8dc48e51b6056f4e.mp3",
    tags: ["老年", "智慧", "爺爺", "慈祥"],
    kreadoVoiceId: "ai_laoguowang_712",
    kreadoVoiceSource: 5,
  },
  "cantonese-elder-female": {
    id: "cantonese-elder-female",
    name: "魏紹蘭",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "elder",
    style: ["character", "storytelling"],
    description: "慈愛溫暖的老年女聲，聲音親切有愛意",
    useCases: ["婆婆角色", "慈母角色", "家庭故事", "溫馨內容"],
    voice: "nova",
    sampleText: "乖孫，嘳食婆婆煢嘊湯啦。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/2bf0384c60b24339ab233156717d1429.mp3",
    tags: ["老年", "慈愛", "婆婆", "溫暖"],
    kreadoVoiceId: "ai_her_06",
    kreadoVoiceSource: 5,
  },
  // === 新增粵語配音員 ===
  "cantonese-male-news": {
    id: "cantonese-male-news",
    name: "新聞男主播",
    gender: "male",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "news"],
    description: "專業新聞主播聲音，清晰權威",
    useCases: ["新聞播報", "資訊內容", "公告通知", "企業宣傳"],
    voice: "alloy",
    sampleText: "各位觀眾朋友，歡迎收看今晚新聞。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/db43a80789d343c6843d3f03191360cd.mp3",
    tags: ["新聞", "主播", "專業", "權威"],
    kreadoVoiceId: "ai_000046",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-news": {
    id: "cantonese-female-news",
    name: "新聞女主播",
    gender: "female",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "news"],
    description: "專業新聞女主播聲音，清晰流暢",
    useCases: ["新聞播報", "資訊內容", "公告通知", "企業宣傳"],
    voice: "nova",
    sampleText: "下面來看今日要聞。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/0c77bb6b9d9146359c7689c5d4a29a15.mp3",
    tags: ["新聞", "女主播", "專業", "清晰"],
    kreadoVoiceId: "ai_jingling",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-commercial": {
    id: "cantonese-male-commercial",
    name: "廣告男聲",
    gender: "male",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "commercial"],
    description: "有感染力的廣告男聲，適合商業宣傳",
    useCases: ["商業廣告", "品牌宣傳", "產品介紹", "促銷內容"],
    voice: "alloy",
    sampleText: "全新產品，給你全新體驗！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/1f67f1eddb54492386bbf979d5d1f55c.mp3",
    tags: ["廣告", "商業", "宣傳", "感染力"],
    kreadoVoiceId: "ai_charming_m_01",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-commercial": {
    id: "cantonese-female-commercial",
    name: "廣告女聲",
    gender: "female",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "commercial"],
    description: "有感染力的廣告女聲，適合商業宣傳",
    useCases: ["商業廣告", "品牌宣傳", "美妆廣告", "生活內容"],
    voice: "nova",
    sampleText: "讓美麗從今天開始！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/d6d1bf3a729f47a0b8884869249b5e3f.mp3",
    tags: ["廣告", "商業", "宣傳", "美麗"],
    kreadoVoiceId: "ai_ganyu",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-gaming": {
    id: "cantonese-male-gaming",
    name: "遊戲男聲",
    gender: "male",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character", "cartoon"],
    description: "熱血激情的遊戲男聲，適合遊戲內容",
    useCases: ["遊戲配音", "電競內容", "動作內容", "年輕化內容"],
    voice: "echo",
    sampleText: "衝啊！我嘳輸的！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/1f67f1eddb54492386bbf979d5d1f55c.mp3",
    tags: ["遊戲", "熱血", "激情", "年輕"],
    kreadoVoiceId: "ai_charming_m_01",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-gaming": {
    id: "cantonese-female-gaming",
    name: "遊戲女聲",
    gender: "female",
    type: "character",
    language: "cantonese",
    ageGroup: "young",
    style: ["character", "cartoon"],
    description: "活潑可愛的遊戲女聲，適合遊戲內容",
    useCases: ["遊戲配音", "電競內容", "可愛角色", "年輕化內容"],
    voice: "shimmer",
    sampleText: "哇！我贏咕！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/f3c24f50d0b8407bbdc56ec79226292b.mp3",
    tags: ["遊戲", "活潑", "可愛", "年輕"],
    kreadoVoiceId: "ai_hutao",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-podcast": {
    id: "cantonese-male-podcast",
    name: "Podcast 男聲",
    gender: "male",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "storytelling"],
    description: "親切自然的 Podcast 男聲，適合訪談和分享",
    useCases: ["Podcast", "訪談節目", "知識分享", "生活內容"],
    voice: "alloy",
    sampleText: "大家好，歡迎嘳到我嘊頻道。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/db43a80789d343c6843d3f03191360cd.mp3",
    tags: ["Podcast", "親切", "自然", "分享"],
    kreadoVoiceId: "ai_000046",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-podcast": {
    id: "cantonese-female-podcast",
    name: "Podcast 女聲",
    gender: "female",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "storytelling"],
    description: "親切自然的 Podcast 女聲，適合訪談和分享",
    useCases: ["Podcast", "訪談節目", "知識分享", "生活內容"],
    voice: "nova",
    sampleText: "今日想同你哋分享一個故事。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/0c77bb6b9d9146359c7689c5d4a29a15.mp3",
    tags: ["Podcast", "親切", "自然", "分享"],
    kreadoVoiceId: "ai_jingling",
    kreadoVoiceSource: 5,
  },
  "cantonese-male-meditation": {
    id: "cantonese-male-meditation",
    name: "冥想男聲",
    gender: "male",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "emotional"],
    description: "平靜舒緩的冥想男聲，適合放鬆內容",
    useCases: ["冥想引導", "放鬆內容", "睡前故事", "治癒內容"],
    voice: "onyx",
    sampleText: "慢慢嘳放鬆，感受你嘊呼吸...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/0c499ea708404312b3a1d3d847c3c3bb.mp3",
    tags: ["冥想", "平靜", "放鬆", "治癒"],
    kreadoVoiceId: "ai_000141",
    kreadoVoiceSource: 5,
  },
  "cantonese-female-meditation": {
    id: "cantonese-female-meditation",
    name: "冥想女聲",
    gender: "female",
    type: "narrator",
    language: "cantonese",
    ageGroup: "adult",
    style: ["narrator", "emotional"],
    description: "平靜舒緩的冥想女聲，適合放鬆內容",
    useCases: ["冥想引導", "放鬆內容", "睡前故事", "治癒內容"],
    voice: "nova",
    sampleText: "合埋雙眼，感受周圍嘊寧靜...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/digitalhuman/voice/default_voice/speech02/d6d1bf3a729f47a0b8884869249b5e3f.mp3",
    tags: ["冥想", "平靜", "放鬆", "治癒"],
    kreadoVoiceId: "ai_ganyu",
    kreadoVoiceSource: 5,
  },
};

// ============================================
// 普通話配音員 (Mandarin) - 字節 voiceSource: 4
// ============================================

export const MANDARIN_VOICE_ACTORS: Record<string, VoiceActorConfig> = {
  // === 男聲 - 成年 ===
  "mandarin-male-narrator": {
    id: "mandarin-male-narrator",
    name: "京腔侃爺",
    gender: "male",
    type: "narrator",
    language: "mandarin",
    ageGroup: "adult",
    style: ["narrator", "storytelling"],
    description: "地道京腔男聲，聲音渾厚有故事感",
    useCases: ["紀錄片旁白", "歷史故事", "北京文化", "傳統內容"],
    voice: "alloy",
    sampleText: "各位观众朋友们，今儿咱们聊聊这北京城的故事...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/7/892ab9f825604370b1ee5c6249ddcb5f.mp3",
    tags: ["京腔", "旁白", "故事", "傳統"],
    kreadoVoiceId: "zh_male_jingqiangkanye_moon_bigtts",
    kreadoVoiceSource: 4,
  },
  "mandarin-male-young": {
    id: "mandarin-male-young",
    name: "陽光青年",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "young",
    style: ["character", "commercial"],
    description: "陽光開朗的年輕男聲，聲音清亮有活力",
    useCases: ["年輕男主角", "青春故事", "活力廣告", "校園內容"],
    voice: "echo",
    sampleText: "嘿，今天天气真不错，一起出去玩吧！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/7/d1e76302e6094344a6f6fddfd0132243.mp3",
    tags: ["陽光", "青年", "活力", "青春"],
    kreadoVoiceId: "zh_male_yangguangqingnian_moon_bigtts",
    kreadoVoiceSource: 4,
  },
  "mandarin-male-mature": {
    id: "mandarin-male-mature",
    name: "淵博小叔",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "middle",
    style: ["character", "professional"],
    description: "成熟知性的男聲，聲音沉穩有學識",
    useCases: ["知識分享", "專業講解", "成熟角色", "商務場合"],
    voice: "onyx",
    sampleText: "让我来给大家分析一下这个问题的本质...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/7/6e518079ab784a8790cc024bd9ffdfc3.mp3",
    tags: ["成熟", "知性", "專業", "學識"],
    kreadoVoiceId: "zh_male_yuanboxiaoshu_moon_bigtts",
    kreadoVoiceSource: 4,
  },
  "mandarin-male-warm": {
    id: "mandarin-male-warm",
    name: "溫暖阿虎",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "adult",
    style: ["character", "emotional"],
    description: "溫暖親切的男聲，聲音有安全感",
    useCases: ["暖男角色", "治癒內容", "家庭故事", "溫馨廣告"],
    voice: "alloy",
    sampleText: "别担心，有我在，一切都会好起来的。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/7/510749d0962c4dc6aea3e683dd32206e.mp3",
    tags: ["溫暖", "親切", "暖男", "治癒"],
    kreadoVoiceId: "zh_male_wennuanahu_moon_bigtts",
    kreadoVoiceSource: 4,
  },
  "mandarin-male-arrogant": {
    id: "mandarin-male-arrogant",
    name: "傲嬌霸總",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "adult",
    style: ["character"],
    description: "霸道總裁風格的男聲，聲音有氣勢",
    useCases: ["霸總角色", "商戰故事", "言情小說", "強勢角色"],
    voice: "onyx",
    sampleText: "这件事，就这么定了，不用再讨论。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/7/31a24d928f834ad188f63a84e06635bc.mp3",
    tags: ["霸道", "總裁", "強勢", "言情"],
    kreadoVoiceId: "zh_male_aojiaobazong_moon_bigtts",
    kreadoVoiceSource: 4,
  },
  "mandarin-male-teen": {
    id: "mandarin-male-teen",
    name: "少年梓辛",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "teen",
    style: ["character", "emotional"],
    description: "清澈少年的男聲，聲音純淨有朝氣",
    useCases: ["少年角色", "校園故事", "青春劇情", "成長故事"],
    voice: "echo",
    sampleText: "我一定要努力，不能让大家失望！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/7/d5cabbceaf6b4582be2bf63a8e61ddd2.mp3",
    tags: ["少年", "清澈", "青春", "成長"],
    kreadoVoiceId: "zh_male_shaonianzixin_moon_bigtts",
    kreadoVoiceSource: 4,
  },
  "mandarin-male-news": {
    id: "mandarin-male-news",
    name: "新聞男聲",
    gender: "male",
    type: "narrator",
    language: "mandarin",
    ageGroup: "adult",
    style: ["news", "professional"],
    description: "標準新聞播報男聲，聲音清晰專業",
    useCases: ["新聞播報", "資訊節目", "正式場合", "官方內容"],
    voice: "alloy",
    sampleText: "各位观众朋友们，欢迎收看今天的新闻节目。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/4/046f8a34166a475792d8ff1b9c82a8ed.mp3",
    tags: ["新聞", "播報", "專業", "正式"],
    kreadoVoiceId: "BV012_streaming",
    kreadoVoiceSource: 4,
  },
  "mandarin-male-magnetic": {
    id: "mandarin-male-magnetic",
    name: "磁性男聲",
    gender: "male",
    type: "narrator",
    language: "mandarin",
    ageGroup: "adult",
    style: ["narrator", "commercial"],
    description: "低沉磁性的男聲，聲音有吸引力",
    useCases: ["品牌廣告", "高端宣傳", "深夜電台", "情感內容"],
    voice: "onyx",
    sampleText: "在这个城市的夜晚，总有一些故事在悄悄发生...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/4/9e93f681a2144c7299b5c5f6b426ea49.mp3",
    tags: ["磁性", "低沉", "廣告", "高端"],
    kreadoVoiceId: "BV006_streaming",
    kreadoVoiceSource: 4,
  },

  // === 女聲 - 成年 ===
  "mandarin-female-narrator": {
    id: "mandarin-female-narrator",
    name: "爽快思思",
    gender: "female",
    type: "narrator",
    language: "mandarin",
    ageGroup: "adult",
    style: ["narrator", "commercial"],
    description: "爽朗大方的女聲，聲音清脆有感染力",
    useCases: ["品牌宣傳", "產品介紹", "活力廣告", "生活分享"],
    voice: "nova",
    sampleText: "大家好，今天给大家分享一个超棒的好物！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/7/46b69611fab64a00bbc192f68bae6c37.mp3",
    tags: ["爽朗", "大方", "廣告", "活力"],
    kreadoVoiceId: "zh_female_shuangkuaisisi_moon_bigtts",
    kreadoVoiceSource: 4,
  },
  "mandarin-female-young": {
    id: "mandarin-female-young",
    name: "鄰家女孩",
    gender: "female",
    type: "character",
    language: "mandarin",
    ageGroup: "young",
    style: ["character", "emotional"],
    description: "親切可愛的女聲，聲音自然有親和力",
    useCases: ["鄰家女孩", "日常對話", "生活故事", "輕鬆內容"],
    voice: "shimmer",
    sampleText: "嘿，你今天看起来心情不错嘛！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/7/00695908c4ae466b9e22a8df9976b970.mp3",
    tags: ["鄰家", "親切", "可愛", "日常"],
    kreadoVoiceId: "zh_female_linjianvhai_moon_bigtts",
    kreadoVoiceSource: 4,
  },
  "mandarin-female-mature": {
    id: "mandarin-female-mature",
    name: "高冷御姐",
    gender: "female",
    type: "character",
    language: "mandarin",
    ageGroup: "adult",
    style: ["character", "professional"],
    description: "高冷氣質的女聲，聲音有距離感和氣場",
    useCases: ["御姐角色", "職場女強人", "高冷美人", "專業場合"],
    voice: "nova",
    sampleText: "这件事，我自有安排，不需要你操心。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/7/30e1cdb01bcd4211b7a3cb682c36614f.mp3",
    tags: ["高冷", "御姐", "氣場", "專業"],
    kreadoVoiceId: "zh_female_gaolengyujie_moon_bigtts",
    kreadoVoiceSource: 4,
  },
  "mandarin-female-sweet": {
    id: "mandarin-female-sweet",
    name: "甜美女聲",
    gender: "female",
    type: "character",
    language: "mandarin",
    ageGroup: "young",
    style: ["character", "assistant"],
    description: "甜美可愛的女聲，聲音軟糯有親和力",
    useCases: ["可愛角色", "客服助手", "甜蜜內容", "少女角色"],
    voice: "shimmer",
    sampleText: "你好呀～有什么可以帮到你的吗？",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/bytedance/zh_female_tianmei_moon_bigtts.mp3",
    tags: ["甜美", "可愛", "助手", "少女"],
    kreadoVoiceId: "zh_female_tianmei_moon_bigtts",
    kreadoVoiceSource: 4,
  },
  "mandarin-female-news": {
    id: "mandarin-female-news",
    name: "新聞女聲",
    gender: "female",
    type: "narrator",
    language: "mandarin",
    ageGroup: "adult",
    style: ["news", "professional"],
    description: "標準新聞播報女聲，聲音清晰專業",
    useCases: ["新聞播報", "資訊節目", "正式場合", "官方內容"],
    voice: "nova",
    sampleText: "各位观众朋友们，欢迎收看今天的新闻节目。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/4/be6804d25bcd482c885b473c074e9513.mp3",
    tags: ["新聞", "播報", "專業", "正式"],
    kreadoVoiceId: "BV011_streaming",
    kreadoVoiceSource: 4,
  },

  // === 童聲 ===
  "mandarin-child-girl": {
    id: "mandarin-child-girl",
    name: "小蘿莉",
    gender: "female",
    type: "character",
    language: "mandarin",
    ageGroup: "child",
    style: ["character", "cartoon"],
    description: "可愛甜美的女童聲，聲音稚嫩有童趣",
    useCases: ["兒童角色", "動畫配音", "兒童節目", "童話故事"],
    voice: "shimmer",
    sampleText: "妈妈，我想吃冰淇淋～",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/4/1537a85c00af4959adc8f641a397a186.mp3",
    tags: ["童聲", "女孩", "可愛", "蘿莉"],
    kreadoVoiceId: "BV064_streaming",
    kreadoVoiceSource: 4,
  },
  "mandarin-child-boy": {
    id: "mandarin-child-boy",
    name: "奶氣萌娃",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "child",
    style: ["character", "cartoon"],
    description: "奶聲奶氣的男童聲，聲音稚嫩可愛",
    useCases: ["兒童角色", "動畫配音", "兒童節目", "童話故事"],
    voice: "echo",
    sampleText: "爸爸，我要玩玩具！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/4/e81cb5aabf964428bddc3815a7e225f7.mp3",
    tags: ["童聲", "男孩", "奶氣", "萌娃"],
    kreadoVoiceId: "BV700_streaming",
    kreadoVoiceSource: 4,
  },
  "mandarin-child-genius": {
    id: "mandarin-child-genius",
    name: "天才童聲",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "child",
    style: ["character"],
    description: "聰明伶俐的童聲，聲音清脆有靈氣",
    useCases: ["小天才角色", "教育內容", "兒童節目", "益智內容"],
    voice: "echo",
    sampleText: "这道题我会！答案是42！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/4/a17d2195284445648d97ecd193f66325.mp3",
    tags: ["童聲", "聰明", "天才", "靈氣"],
    kreadoVoiceId: "BV701_streaming",
    kreadoVoiceSource: 4,
  },

  // === 老年聲 ===
  "mandarin-elder-male": {
    id: "mandarin-elder-male",
    name: "智慧老者",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "elder",
    style: ["character", "storytelling"],
    description: "慈祥智慧的老年男聲，聲音沉穩有歷練",
    useCases: ["爺爺角色", "智者角色", "歷史故事", "人生哲理"],
    voice: "fable",
    sampleText: "年轻人，听老夫给你讲个故事...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/4/e7dea5e12c9645de90c7531809bf11a4.mp3",
    tags: ["老年", "智慧", "爺爺", "慈祥"],
    kreadoVoiceId: "BV157_streaming",
    kreadoVoiceSource: 4,
  },
  "mandarin-elder-female": {
    id: "mandarin-elder-female",
    name: "慈愛姥姥",
    gender: "female",
    type: "character",
    language: "mandarin",
    ageGroup: "elder",
    style: ["character", "storytelling"],
    description: "慈愛溫暖的老年女聲，聲音親切有愛意",
    useCases: ["奶奶角色", "慈母角色", "家庭故事", "溫馨內容"],
    voice: "nova",
    sampleText: "乖孙子，来吃姥姥做的饭。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice_new/audio/2024/4/3bdc9ccf0126439b9a12970d69513a8d.mp3",
    tags: ["老年", "慈愛", "姥姥", "溫暖"],
    kreadoVoiceId: "BV158_streaming",
    kreadoVoiceSource: 4,
  },

  // === 特殊角色 ===
  "mandarin-cartoon-sponge": {
    id: "mandarin-cartoon-sponge",
    name: "動漫海綿",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "child",
    style: ["cartoon"],
    description: "海綿寶寶風格的聲音，聲音搞笑有趣",
    useCases: ["卡通角色", "搞笑內容", "兒童動畫", "趣味配音"],
    voice: "echo",
    sampleText: "我准备好了！我准备好了！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/bytedance/BV702_streaming.mp3",
    tags: ["卡通", "搞笑", "海綿寶寶", "趣味"],
    kreadoVoiceId: "BV702_streaming",
    kreadoVoiceSource: 4,
  },
  "mandarin-cartoon-star": {
    id: "mandarin-cartoon-star",
    name: "動漫海星",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "child",
    style: ["cartoon"],
    description: "派大星風格的聲音，聲音呆萌有趣",
    useCases: ["卡通角色", "搞笑內容", "兒童動畫", "趣味配音"],
    voice: "echo",
    sampleText: "这是什么？能吃吗？",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/bytedance/BV703_streaming.mp3",
    tags: ["卡通", "呆萌", "派大星", "趣味"],
    kreadoVoiceId: "BV703_streaming",
    kreadoVoiceSource: 4,
  },
  // === 新增普通話配音員 ===
  "mandarin-male-deep": {
    id: "mandarin-male-deep",
    name: "深沉男中音",
    gender: "male",
    type: "narrator",
    language: "mandarin",
    ageGroup: "adult",
    style: ["narrator", "professional"],
    description: "深沉有磁性的男聲，適合紀錄片旁白",
    useCases: ["紀錄片", "新聞播報", "商業廣告", "有聲書"],
    voice: "onyx",
    sampleText: "在这个充满变革的时代...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/bytedance/BV001_streaming.mp3",
    tags: ["深沉", "磁性", "旁白", "專業"],
    kreadoVoiceId: "BV001_streaming",
    kreadoVoiceSource: 4,
  },
  "mandarin-male-energetic": {
    id: "mandarin-male-energetic",
    name: "活力男聲",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "young",
    style: ["character", "commercial"],
    description: "充满活力的年輕男聲，適合廣告和運動內容",
    useCases: ["運動廣告", "遊戲宣傳", "年輕化內容", "社交媒體"],
    voice: "echo",
    sampleText: "冲啊！让我们一起起飞！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/bytedance/BV700_streaming.mp3",
    tags: ["活力", "年輕", "運動", "廣告"],
    kreadoVoiceId: "BV700_streaming",
    kreadoVoiceSource: 4,
  },
  "mandarin-female-elegant": {
    id: "mandarin-female-elegant",
    name: "優雅女聲",
    gender: "female",
    type: "narrator",
    language: "mandarin",
    ageGroup: "adult",
    style: ["narrator", "professional"],
    description: "優雅知性的女聲，適合品牌宣傳",
    useCases: ["品牌宣傳", "奢侈品廣告", "文化內容", "教育課程"],
    voice: "nova",
    sampleText: "让我们一起探索美的真谛。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/bytedance/BV007_streaming.mp3",
    tags: ["優雅", "知性", "品牌", "專業"],
    kreadoVoiceId: "BV007_streaming",
    kreadoVoiceSource: 4,
  },
  "mandarin-female-lively": {
    id: "mandarin-female-lively",
    name: "活潑女聲",
    gender: "female",
    type: "character",
    language: "mandarin",
    ageGroup: "teen",
    style: ["character", "cartoon"],
    description: "活潑開朗的女聲，適合年輕化內容",
    useCases: ["卡通角色", "年輕化內容", "遊戲配音", "社交媒體"],
    voice: "shimmer",
    sampleText: "哇！这也太棒了吧！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/bytedance/BV034_streaming.mp3",
    tags: ["活潑", "開朗", "年輕", "卡通"],
    kreadoVoiceId: "BV034_streaming",
    kreadoVoiceSource: 4,
  },
  "mandarin-male-elderly": {
    id: "mandarin-male-elderly",
    name: "老者男聲",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "elder",
    style: ["character", "storytelling"],
    description: "溫和智慧的老者聲音，適合講述故事",
    useCases: ["祖父角色", "歷史故事", "智慧分享", "傳統文化"],
    voice: "onyx",
    sampleText: "孩子们，让我给你们讲个故事...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/bytedance/BV001_streaming.mp3",
    tags: ["老者", "智慧", "故事", "祖父"],
    kreadoVoiceId: "BV001_streaming",
    kreadoVoiceSource: 4,
  },
  "mandarin-female-elderly": {
    id: "mandarin-female-elderly",
    name: "老者女聲",
    gender: "female",
    type: "character",
    language: "mandarin",
    ageGroup: "elder",
    style: ["character", "storytelling"],
    description: "溫柔慈祥的老者女聲，適合家庭內容",
    useCases: ["祖母角色", "家庭故事", "傳統文化", "治癒內容"],
    voice: "nova",
    sampleText: "来，孩子，奶奶给你做好吃的。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/bytedance/BV007_streaming.mp3",
    tags: ["老者", "溫柔", "祖母", "家庭"],
    kreadoVoiceId: "BV007_streaming",
    kreadoVoiceSource: 4,
  },
  "mandarin-male-child": {
    id: "mandarin-male-child",
    name: "男童聲",
    gender: "male",
    type: "character",
    language: "mandarin",
    ageGroup: "child",
    style: ["character", "cartoon"],
    description: "可愛的男童聲音，適合兒童內容",
    useCases: ["兒童角色", "動畫配音", "兒童節目", "故事朗讀"],
    voice: "echo",
    sampleText: "妈妈，我想吃冰淇淋！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/bytedance/BV700_streaming.mp3",
    tags: ["男童", "可愛", "兒童", "卡通"],
    kreadoVoiceId: "BV700_streaming",
    kreadoVoiceSource: 4,
  },
  "mandarin-female-child": {
    id: "mandarin-female-child",
    name: "女童聲",
    gender: "female",
    type: "character",
    language: "mandarin",
    ageGroup: "child",
    style: ["character", "cartoon"],
    description: "甜美的女童聲音，適合兒童內容",
    useCases: ["兒童角色", "動畫配音", "兒童節目", "故事朗讀"],
    voice: "shimmer",
    sampleText: "爸爸，看我的新裙子！",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/bytedance/BV034_streaming.mp3",
    tags: ["女童", "甜美", "兒童", "卡通"],
    kreadoVoiceId: "BV034_streaming",
    kreadoVoiceSource: 4,
  },
};

// ============================================
// 英語配音員 (English) - ElevenLabs voiceSource: 21
// ============================================

export const ENGLISH_VOICE_ACTORS: Record<string, VoiceActorConfig> = {
  "english-male-narrator": {
    id: "english-male-narrator",
    name: "Alyx",
    gender: "male",
    type: "narrator",
    language: "english",
    ageGroup: "adult",
    style: ["narrator", "professional"],
    description: "Vibrant British male voice, clear and engaging",
    useCases: ["Documentary narration", "Audiobooks", "Brand promotion", "Educational content"],
    voice: "alloy",
    sampleText: "Welcome to our journey through the fascinating world of science and discovery.",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/1BUhH8aaMvGMUdGAmWVM.mp3",
    tags: ["British", "narrator", "professional", "engaging"],
    kreadoVoiceId: "1BUhH8aaMvGMUdGAmWVM",
    kreadoVoiceSource: 21,
  },
  "english-male-young": {
    id: "english-male-young",
    name: "Johnny Kid",
    gender: "male",
    type: "character",
    language: "english",
    ageGroup: "young",
    style: ["character", "commercial"],
    description: "Youthful energetic male voice, friendly and approachable",
    useCases: ["Young male characters", "Casual content", "Gaming", "Youth marketing"],
    voice: "echo",
    sampleText: "Hey there! Ready to have some fun?",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/8JVbfL6oEdmuxKn5DK2C.mp3",
    tags: ["young", "energetic", "friendly", "casual"],
    kreadoVoiceId: "8JVbfL6oEdmuxKn5DK2C",
    kreadoVoiceSource: 21,
  },
  "english-male-mature": {
    id: "english-male-mature",
    name: "Christopher",
    gender: "male",
    type: "character",
    language: "english",
    ageGroup: "middle",
    style: ["character", "professional"],
    description: "Mature authoritative male voice, commanding and trustworthy",
    useCases: ["Authority figures", "Business content", "Father roles", "Corporate narration"],
    voice: "onyx",
    sampleText: "Let me explain the situation clearly and thoroughly.",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/G17SuINrv2H9FC6nvetn.mp3",
    tags: ["mature", "authoritative", "professional", "trustworthy"],
    kreadoVoiceId: "G17SuINrv2H9FC6nvetn",
    kreadoVoiceSource: 21,
  },
  "english-female-narrator": {
    id: "english-female-narrator",
    name: "Samara X",
    gender: "female",
    type: "narrator",
    language: "english",
    ageGroup: "adult",
    style: ["narrator", "storytelling"],
    description: "Warm elegant female voice, soothing and captivating",
    useCases: ["Audiobook narration", "Documentary", "Brand storytelling", "Meditation content"],
    voice: "nova",
    sampleText: "In the quiet moments of the evening, stories come alive...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/19STyYD15bswVz51nqLf.mp3",
    tags: ["warm", "elegant", "narrator", "soothing"],
    kreadoVoiceId: "19STyYD15bswVz51nqLf",
    kreadoVoiceSource: 21,
  },
  "english-female-young": {
    id: "english-female-young",
    name: "Elli",
    gender: "female",
    type: "character",
    language: "english",
    ageGroup: "young",
    style: ["character", "emotional"],
    description: "Sweet gentle female voice, friendly and approachable",
    useCases: ["Young female characters", "Romance stories", "Casual content", "Customer service"],
    voice: "shimmer",
    sampleText: "Oh, that's so lovely! I can't believe it!",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/09AoN6tYyW3VSTQqCo7C.mp3",
    tags: ["sweet", "gentle", "friendly", "young"],
    kreadoVoiceId: "09AoN6tYyW3VSTQqCo7C",
    kreadoVoiceSource: 21,
  },
  "english-female-mature": {
    id: "english-female-mature",
    name: "Dorothy",
    gender: "female",
    type: "character",
    language: "english",
    ageGroup: "middle",
    style: ["character", "professional"],
    description: "Classic elegant female voice, warm and sophisticated",
    useCases: ["Mature female characters", "Classic stories", "Luxury brands", "Professional content"],
    voice: "nova",
    sampleText: "There's no place like home, my dear.",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/Se2Vw1WbHmGbBbyWTuu4.mp3",
    tags: ["classic", "elegant", "warm", "sophisticated"],
    kreadoVoiceId: "Se2Vw1WbHmGbBbyWTuu4",
    kreadoVoiceSource: 21,
  },
  // === 童聲 ===
  "english-child-boy": {
    id: "english-child-boy",
    name: "Tommy Boy",
    gender: "male",
    type: "character",
    language: "english",
    ageGroup: "child",
    style: ["character", "cartoon"],
    description: "Cute energetic boy voice, playful and cheerful",
    useCases: ["Children characters", "Animation dubbing", "Kids shows", "Fairy tales"],
    voice: "echo",
    sampleText: "Mommy, can I have some ice cream please?",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/8JVbfL6oEdmuxKn5DK2C.mp3",
    tags: ["child", "boy", "cute", "energetic"],
    kreadoVoiceId: "8JVbfL6oEdmuxKn5DK2C",
    kreadoVoiceSource: 21,
  },
  "english-child-girl": {
    id: "english-child-girl",
    name: "Lily Girl",
    gender: "female",
    type: "character",
    language: "english",
    ageGroup: "child",
    style: ["character", "cartoon"],
    description: "Sweet adorable girl voice, innocent and charming",
    useCases: ["Children characters", "Animation dubbing", "Kids shows", "Fairy tales"],
    voice: "shimmer",
    sampleText: "Daddy, look at my pretty dress!",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/09AoN6tYyW3VSTQqCo7C.mp3",
    tags: ["child", "girl", "sweet", "adorable"],
    kreadoVoiceId: "09AoN6tYyW3VSTQqCo7C",
    kreadoVoiceSource: 21,
  },
  // === 新增英語配音員 ===
  "english-male-deep": {
    id: "english-male-deep",
    name: "Marcus",
    gender: "male",
    type: "narrator",
    language: "english",
    ageGroup: "adult",
    style: ["narrator", "professional"],
    description: "Deep resonant male voice, perfect for dramatic content",
    useCases: ["Movie trailers", "Documentary", "Dramatic narration", "Audiobooks"],
    voice: "onyx",
    sampleText: "In a world where everything changed...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/G17SuINrv2H9FC6nvetn.mp3",
    tags: ["deep", "dramatic", "narrator", "powerful"],
    kreadoVoiceId: "G17SuINrv2H9FC6nvetn",
    kreadoVoiceSource: 21,
  },
  "english-male-friendly": {
    id: "english-male-friendly",
    name: "Ryan",
    gender: "male",
    type: "character",
    language: "english",
    ageGroup: "young",
    style: ["character", "commercial"],
    description: "Friendly approachable male voice, great for ads",
    useCases: ["Commercials", "Explainer videos", "Tutorials", "Podcasts"],
    voice: "echo",
    sampleText: "Hey everyone, let me show you something amazing!",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/8JVbfL6oEdmuxKn5DK2C.mp3",
    tags: ["friendly", "approachable", "commercial", "casual"],
    kreadoVoiceId: "8JVbfL6oEdmuxKn5DK2C",
    kreadoVoiceSource: 21,
  },
  "english-male-news": {
    id: "english-male-news",
    name: "Anderson",
    gender: "male",
    type: "narrator",
    language: "english",
    ageGroup: "middle",
    style: ["narrator", "news"],
    description: "Professional news anchor voice, clear and authoritative",
    useCases: ["News reading", "Reports", "Announcements", "Corporate videos"],
    voice: "alloy",
    sampleText: "Breaking news from around the world tonight.",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/1BUhH8aaMvGMUdGAmWVM.mp3",
    tags: ["news", "anchor", "professional", "authoritative"],
    kreadoVoiceId: "1BUhH8aaMvGMUdGAmWVM",
    kreadoVoiceSource: 21,
  },
  "english-female-cheerful": {
    id: "english-female-cheerful",
    name: "Jessica",
    gender: "female",
    type: "character",
    language: "english",
    ageGroup: "young",
    style: ["character", "commercial"],
    description: "Cheerful energetic female voice, upbeat and positive",
    useCases: ["Commercials", "Social media", "Lifestyle content", "Promotions"],
    voice: "shimmer",
    sampleText: "This is going to be absolutely amazing!",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/09AoN6tYyW3VSTQqCo7C.mp3",
    tags: ["cheerful", "energetic", "upbeat", "positive"],
    kreadoVoiceId: "09AoN6tYyW3VSTQqCo7C",
    kreadoVoiceSource: 21,
  },
  "english-female-calm": {
    id: "english-female-calm",
    name: "Sarah",
    gender: "female",
    type: "narrator",
    language: "english",
    ageGroup: "adult",
    style: ["narrator", "emotional"],
    description: "Calm soothing female voice, perfect for meditation",
    useCases: ["Meditation", "ASMR", "Relaxation", "Sleep stories"],
    voice: "nova",
    sampleText: "Take a deep breath and let yourself relax...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/19STyYD15bswVz51nqLf.mp3",
    tags: ["calm", "soothing", "meditation", "relaxing"],
    kreadoVoiceId: "19STyYD15bswVz51nqLf",
    kreadoVoiceSource: 21,
  },
  "english-female-professional": {
    id: "english-female-professional",
    name: "Victoria",
    gender: "female",
    type: "narrator",
    language: "english",
    ageGroup: "adult",
    style: ["narrator", "professional"],
    description: "Professional business female voice, confident and clear",
    useCases: ["Corporate videos", "Presentations", "E-learning", "Business content"],
    voice: "nova",
    sampleText: "Let's discuss the key points of today's presentation.",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/Se2Vw1WbHmGbBbyWTuu4.mp3",
    tags: ["professional", "business", "confident", "clear"],
    kreadoVoiceId: "Se2Vw1WbHmGbBbyWTuu4",
    kreadoVoiceSource: 21,
  },
  "english-male-elderly": {
    id: "english-male-elderly",
    name: "Grandpa Joe",
    gender: "male",
    type: "character",
    language: "english",
    ageGroup: "elder",
    style: ["character", "storytelling"],
    description: "Warm elderly male voice, wise and comforting",
    useCases: ["Grandfather roles", "Storytelling", "Wisdom content", "Historical narration"],
    voice: "onyx",
    sampleText: "Let me tell you a story from long ago...",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/G17SuINrv2H9FC6nvetn.mp3",
    tags: ["elderly", "wise", "warm", "grandfather"],
    kreadoVoiceId: "G17SuINrv2H9FC6nvetn",
    kreadoVoiceSource: 21,
  },
  "english-female-elderly": {
    id: "english-female-elderly",
    name: "Grandma Rose",
    gender: "female",
    type: "character",
    language: "english",
    ageGroup: "elder",
    style: ["character", "storytelling"],
    description: "Gentle elderly female voice, nurturing and kind",
    useCases: ["Grandmother roles", "Bedtime stories", "Family content", "Nostalgic narration"],
    voice: "nova",
    sampleText: "Come here, dear, let me tell you about the old days.",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/Se2Vw1WbHmGbBbyWTuu4.mp3",
    tags: ["elderly", "gentle", "nurturing", "grandmother"],
    kreadoVoiceId: "Se2Vw1WbHmGbBbyWTuu4",
    kreadoVoiceSource: 21,
  },
  "english-male-teen": {
    id: "english-male-teen",
    name: "Jake",
    gender: "male",
    type: "character",
    language: "english",
    ageGroup: "teen",
    style: ["character", "cartoon"],
    description: "Teenage male voice, cool and trendy",
    useCases: ["Teen characters", "Gaming content", "Youth shows", "Social media"],
    voice: "echo",
    sampleText: "Dude, that was totally epic!",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/8JVbfL6oEdmuxKn5DK2C.mp3",
    tags: ["teen", "cool", "trendy", "youth"],
    kreadoVoiceId: "8JVbfL6oEdmuxKn5DK2C",
    kreadoVoiceSource: 21,
  },
  "english-female-teen": {
    id: "english-female-teen",
    name: "Emma",
    gender: "female",
    type: "character",
    language: "english",
    ageGroup: "teen",
    style: ["character", "emotional"],
    description: "Teenage female voice, expressive and relatable",
    useCases: ["Teen characters", "Drama content", "Youth shows", "Coming-of-age stories"],
    voice: "shimmer",
    sampleText: "Oh my gosh, you won't believe what happened!",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/elevenlabs/09AoN6tYyW3VSTQqCo7C.mp3",
    tags: ["teen", "expressive", "relatable", "youth"],
    kreadoVoiceId: "09AoN6tYyW3VSTQqCo7C",
    kreadoVoiceSource: 21,
  },
};

// ============================================
// 克隆聲音 (Clone Voices)
// ============================================

export const CLONE_VOICE_ACTORS: Record<string, VoiceActorConfig> = {
  "clone-po": {
    id: "clone-po",
    name: "PO（克隆）",
    gender: "male",
    type: "narrator",
    language: "clone",
    ageGroup: "adult",
    style: ["narrator", "storytelling"],
    description: "PO 的克隆語音，粵語發音，聲音自然真實",
    useCases: ["個人品牌", "自媒體內容", "旁白敘述", "個性化配音"],
    voice: "alloy",
    sampleText: "大家好，歡迎嚟到我嘅頻道。",
    sampleUrl: "https://aigc-cdn.kreadoai.com/default_voice/audio/2025/12/eaf6d307ffaf43a694f487dbfd138bc7.mp3",
    tags: ["克隆", "PO", "粵語", "旁白", "個人", "自然"],
    kreadoVoiceId: "Minimax919724_52965111962639",
    kreadoVoiceSource: 5,
    kreadoLanguageId: "1767068435675340826",
  },
};

// ============================================
// 合併所有配音員
// ============================================

export const ALL_VOICE_ACTORS: Record<string, VoiceActorConfig> = {
  ...CANTONESE_VOICE_ACTORS,
  ...MANDARIN_VOICE_ACTORS,
  ...ENGLISH_VOICE_ACTORS,
  ...CLONE_VOICE_ACTORS,
};

// ============================================
// 篩選輔助函數
// ============================================

// 按語言篩選
export function filterByLanguage(language: VoiceLanguage): VoiceActorConfig[] {
  return Object.values(ALL_VOICE_ACTORS).filter(actor => actor.language === language);
}

// 按性別篩選
export function filterByGender(gender: "male" | "female"): VoiceActorConfig[] {
  return Object.values(ALL_VOICE_ACTORS).filter(actor => actor.gender === gender);
}

// 按年齡段篩選
export function filterByAgeGroup(ageGroup: AgeGroup): VoiceActorConfig[] {
  return Object.values(ALL_VOICE_ACTORS).filter(actor => actor.ageGroup === ageGroup);
}

// 按風格篩選
export function filterByStyle(style: VoiceStyle): VoiceActorConfig[] {
  return Object.values(ALL_VOICE_ACTORS).filter(actor => actor.style.includes(style));
}

// 組合篩選
export function filterVoiceActors(options: {
  language?: VoiceLanguage;
  gender?: "male" | "female";
  ageGroup?: AgeGroup;
  style?: VoiceStyle;
}): VoiceActorConfig[] {
  let result = Object.values(ALL_VOICE_ACTORS);
  
  if (options.language) {
    result = result.filter(actor => actor.language === options.language);
  }
  if (options.gender) {
    result = result.filter(actor => actor.gender === options.gender);
  }
  if (options.ageGroup) {
    result = result.filter(actor => actor.ageGroup === options.ageGroup);
  }
  if (options.style) {
    result = result.filter(actor => options.style && actor.style.includes(options.style));
  }
  
  return result;
}

// 獲取配音員統計
export function getVoiceActorStats() {
  const actors = Object.values(ALL_VOICE_ACTORS);
  
  return {
    total: actors.length,
    byLanguage: {
      cantonese: actors.filter(a => a.language === "cantonese").length,
      mandarin: actors.filter(a => a.language === "mandarin").length,
      english: actors.filter(a => a.language === "english").length,
      clone: actors.filter(a => a.language === "clone").length,
    },
    byGender: {
      male: actors.filter(a => a.gender === "male").length,
      female: actors.filter(a => a.gender === "female").length,
    },
    byAgeGroup: {
      child: actors.filter(a => a.ageGroup === "child").length,
      teen: actors.filter(a => a.ageGroup === "teen").length,
      young: actors.filter(a => a.ageGroup === "young").length,
      adult: actors.filter(a => a.ageGroup === "adult").length,
      middle: actors.filter(a => a.ageGroup === "middle").length,
      elder: actors.filter(a => a.ageGroup === "elder").length,
    },
  };
}
